version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: gp_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: sendvoyage
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/db/schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
